services:
  - type: web
    name: omni-reception
    runtime: node
    plan: free
    autoDeploy: true
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Optional secrets for production; set these in Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
    healthCheckPath: /health
